
FROM ubuntu:artful
MAINTAINER tracey

ADD images    /app/images/
ADD includes  /app/includes/
ADD jw        /app/jw/
WORKDIR       /app/

RUN apt-get update  &&  apt-get install -y npm  nodejs  zsh  sudo  git

# upgrade npm!  add respawner pkg
RUN npm install -g npm@latest supervisor

# add npm pkgs we use
ADD includes/node/package.json /app/
RUN npm install

RUN rm -rf                    /app/includes/node_modules  # needed?
RUN ln -s  /app/node_modules  /app/includes/node_modules  # needed!

# allow http
EXPOSE 80 3000

# when this container is invoked like "docker exec .." this is what that will run
CMD [ "/usr/local/bin/supervisor", "--watch", "includes/node", "includes/node/Main.js" ]

# to do active dev/changes to JS files, see "run.sh" in this same dir
